# Generated by Django 4.1 on 2022-08-10 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_rename_email_confirmed_user_email_verified"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="login_method",
            field=models.CharField(
                choices=[
                    ("email", "Email"),
                    ("google", "Google"),
                    ("facebook", "Facebook"),
                ],
                default="email",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="email_secret",
            field=models.CharField(blank=True, default="", max_length=20),
        ),
    ]
